[project]
name = "fastapi-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shubham_sawant", email = "shubham.s@techtps.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.142.2",
]

[project.scripts]
fastapi-blog = "fastapi_blog:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
